version: "3.4"

services:
  frontend:
    image: sa_portal_frontend
    container_name: sa_portal_frontend
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "3026:3000"