import React from 'react'
import Teams from '../../components/teams/teams'
import Footer from '@/components/Footer/Footer.js'
import Navbar from '@/components/Navbar/Navbar'


const props = {
    "buttons":[
        "SA Functionaries",
        "Board Functionaries",
        "Students' Gymkhana",
        "SA Staff",
        "Gymkhana Staff"
    ],
    "SAFunctionaries":[
        {
            "image":"https://images.pexels.com/photos/1261728/pexels-photo-1261728.jpeg?auto=compress&cs=tinysrgb&w=600",
        "phone":"9797997979",
        "link":"/teams",
        "designation":"efaeaefawf",
        "name":"aefaefaef",
        "buttons":[
            {
                "id":1,
                "value":"efewfe"
            },
            {
                "id":2,
                "value":"efewfe"
            },
            {
                "id":3,
                "value":"efewfe"
            }
        ]
        },
        {
            "image":"https://images.pexels.com/photos/1261728/pexels-photo-1261728.jpeg?auto=compress&cs=tinysrgb&w=600",
            "phone":"9797997979",
            "link":"/teams",
            "designation":"efaeaefawf",
            "name":"aefaefaef",
            "buttons":[
                {
                    "id":1,
                    "value":"efewfe"
                },
                {
                    "id":2,
                    "value":"efewfe"
                },
                {
                    "id":3,
                    "value":"efewfe"
                }
            ]
            },
            {
                "image":"https://images.pexels.com/photos/1261728/pexels-photo-1261728.jpeg?auto=compress&cs=tinysrgb&w=600",
                "phone":"9797997979",
                "link":"/teams",
                "designation":"efaeaefawf",
                "name":"aefaefaef",
                "buttons":[
                    {
                        "id":1,
                        "value":"efewfe"
                    },
                    {
                        "id":2,
                        "value":"efewfe"
                    },
                    {
                        "id":3,
                        "value":"efewfe"
                    }
                ]
                },        
    ],
    "BoardFunctionaries":[
        {
            "image":"https://images.pexels.com/photos/1261728/pexels-photo-1261728.jpeg?auto=compress&cs=tinysrgb&w=600",
        "phone":"9797997979",
        "link":"/teams",
        "designation":"efaeaefawf",
        "name":"aefaefaef",
        "buttons":[
            {
                "id":1,
                "value":"efewfe"
            },
            {
                "id":2,
                "value":"efewfe"
            },
            {
                "id":3,
                "value":"efewfe"
            }
        ]
        },
        {
            "image":"https://images.pexels.com/photos/1261728/pexels-photo-1261728.jpeg?auto=compress&cs=tinysrgb&w=600",
            "phone":"9797997979",
            "link":"/teams",
            "designation":"efaeaefawf",
            "name":"aefaefaef",
            "buttons":[
                {
                    "id":1,
                    "value":"efewfe"
                },
                {
                    "id":2,
                    "value":"efewfe"
                },
                {
                    "id":3,
                    "value":"efewfe"
                }
            ]
            },
            {
                "image":"https://images.pexels.com/photos/1261728/pexels-photo-1261728.jpeg?auto=compress&cs=tinysrgb&w=600",
                "phone":"9797997979",
                "link":"/teams",
                "designation":"efaeaefawf",
                "name":"aefaefaef",
                "buttons":[
                    {
                        "id":1,
                        "value":"efewfe"
                    },
                    {
                        "id":2,
                        "value":"efewfe"
                    },
                    {
                        "id":3,
                        "value":"efewfe"
                    }
                ]
                },        
    ],
    "StudentsGymkhana":[
        {
            "image":"https://images.pexels.com/photos/1261728/pexels-photo-1261728.jpeg?auto=compress&cs=tinysrgb&w=600",
        "phone":"9797997979",
        "link":"/teams",
        "designation":"efaeaefawf",
        "name":"aefaefaef",
        "buttons":[
            {
                "id":1,
                "value":"efewfe"
            },
            {
                "id":2,
                "value":"efewfe"
            },
            {
                "id":3,
                "value":"efewfe"
            }
        ]
        },
        {
            "image":"https://images.pexels.com/photos/1261728/pexels-photo-1261728.jpeg?auto=compress&cs=tinysrgb&w=600",
            "phone":"9797997979",
            "link":"/teams",
            "designation":"efaeaefawf",
            "name":"aefaefaef",
            "buttons":[
                {
                    "id":1,
                    "value":"efewfe"
                },
                {
                    "id":2,
                    "value":"efewfe"
                },
                {
                    "id":3,
                    "value":"efewfe"
                }
            ]
            },
            {
                "image":"https://images.pexels.com/photos/1261728/pexels-photo-1261728.jpeg?auto=compress&cs=tinysrgb&w=600",
                "phone":"9797997979",
                "link":"/teams",
                "designation":"efaeaefawf",
                "name":"aefaefaef",
                "buttons":[
                    {
                        "id":1,
                        "value":"efewfe"
                    },
                    {
                        "id":2,
                        "value":"efewfe"
                    },
                    {
                        "id":3,
                        "value":"efewfe"
                    }
                ]
                },        
    ],
    "SAStaff":[
        {
            "image":"https://images.pexels.com/photos/1261728/pexels-photo-1261728.jpeg?auto=compress&cs=tinysrgb&w=600",
        "phone":"9797997979",
        "link":"/teams",
        "designation":"efaeaefawf",
        "name":"aefaefaef",
        "buttons":[
            {
                "id":1,
                "value":"efewfe"
            },
            {
                "id":2,
                "value":"efewfe"
            },
            {
                "id":3,
                "value":"efewfe"
            }
        ]
        },
        {
            "image":"https://images.pexels.com/photos/1261728/pexels-photo-1261728.jpeg?auto=compress&cs=tinysrgb&w=600",
            "phone":"9797997979",
            "link":"/teams",
            "designation":"efaeaefawf",
            "name":"aefaefaef",
            "buttons":[
                {
                    "id":1,
                    "value":"efewfe"
                },
                {
                    "id":2,
                    "value":"efewfe"
                },
                {
                    "id":3,
                    "value":"efewfe"
                }
            ]
            },
            {
                "image":"https://images.pexels.com/photos/1261728/pexels-photo-1261728.jpeg?auto=compress&cs=tinysrgb&w=600",
                "phone":"9797997979",
                "link":"/teams",
                "designation":"efaeaefawf",
                "name":"aefaefaef",
                "buttons":[
                    {
                        "id":1,
                        "value":"efewfe"
                    },
                    {
                        "id":2,
                        "value":"efewfe"
                    },
                    {
                        "id":3,
                        "value":"efewfe"
                    }
                ]
                },        
    ],
    "GymkhanaStaff":[
        {
            "image":"https://images.pexels.com/photos/1261728/pexels-photo-1261728.jpeg?auto=compress&cs=tinysrgb&w=600",
        "phone":"9797997979",
        "link":"/teams",
        "designation":"efaeaefawf",
        "name":"aefaefaef",
        "buttons":[
            {
                "id":1,
                "value":"efewfe"
            },
            {
                "id":2,
                "value":"efewfe"
            },
            {
                "id":3,
                "value":"efewfe"
            }
        ]
        },
        {
            "image":"https://images.pexels.com/photos/1261728/pexels-photo-1261728.jpeg?auto=compress&cs=tinysrgb&w=600",
            "phone":"9797997979",
            "link":"/teams",
            "designation":"efaeaefawf",
            "name":"aefaefaef",
            "buttons":[
                {
                    "id":1,
                    "value":"efewfe"
                },
                {
                    "id":2,
                    "value":"efewfe"
                },
                {
                    "id":3,
                    "value":"efewfe"
                }
            ]
            },
            {
                "image":"https://images.pexels.com/photos/1261728/pexels-photo-1261728.jpeg?auto=compress&cs=tinysrgb&w=600",
                "phone":"9797997979",
                "link":"/teams",
                "designation":"efaeaefawf",
                "name":"aefaefaef",
                "buttons":[
                    {
                        "id":1,
                        "value":"efewfe"
                    },
                    {
                        "id":2,
                        "value":"efewfe"
                    },
                    {
                        "id":3,
                        "value":"efewfe"
                    }
                ]
                },        
    ]
}

const index = () => {
  return (
    <div>
        <Navbar/>
        <Teams prop = {props} />
        <Footer/>
    </div>
  )
}

export default index;